copy D:\devLibs\Framework\DevExpress.BonusSkins.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Charts.Designer.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Charts.v15.1.Core.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.CodeParser.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Data.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.DataAccess.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.DataAccess.v15.1.UI.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.DevAV.v15.1.Data.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.DevAV.v15.1.Reports.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.ExpressApp.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.ExpressApp.Win.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Map.v15.1.Core.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Mvvm.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Office.v15.1.Core.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.PivotGrid.v15.1.Core.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Printing.v15.1.Core.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.RichEdit.v15.1.Core.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Sparkline.v15.1.Core.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Utils.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Utils.v15.1.UI.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.Xpf.Map.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraBars.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraCharts.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraCharts.v15.1.Extensions.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraCharts.v15.1.UI.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraCharts.v15.1.Web.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraCharts.v15.1.Wizard.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraEditors.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraGauges.v15.1.Core.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraGrid.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraLayout.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraMap.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraNavBar.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraPivotGrid.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraPrinting.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraReports.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraReports.v15.1.Extensions.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraRichEdit.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraTreeList.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy D:\devLibs\Framework\DevExpress.XtraVerticalGrid.v15.1.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy C:\Program Files (x86)\FlexCell Technologies\FlexCell.NET2\Bin\FlexCell.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all
copy E:\source\ZTClient\DLL\Zhuantou.Control.Client.DataGrid.dll E:\my\xuangua\Suspension_TaoBao\source\Libs\dev\dev_all

